// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'releaseSeason': string;
  'season': string;
  'source': string;
}
export const cssExports: CssExports;
export default cssExports;
