// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAlias': string;
  'noAliases': string;
  'sceneMappingInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
